name: Build and Push Docker Images

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/setup-php.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PHP_EXTENSIONS: ${{ vars.PHP_EXTENSIONS }}
  DOCKER_BUILD_RECORD_UPLOAD: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    # 【關鍵】定義矩陣策略，同時跑 4 個版本
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get current date
        id: date
        run: echo "today=$(TZ=Asia/Taipei date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Get latest release version
        id: action_runner_version
        env:
          GH_TOKEN: ${{ github.token }} # 必須提供 Token 避免 API 限制
        run: |
          # 使用 gh cli 取得 tag name
          TAG_NAME=$(gh release view --repo actions/runner --json tagName --jq .tagName)
          
          # 去掉開頭的 v
          VERSION=${TAG_NAME#v}
          
          echo "Detected version: $VERSION"
          
          # 寫入 output 供後續步驟使用
          echo "runner_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # 這裡設定 Tag 規則，例如 ghcr.io/user/repo:8.1
          tags: |
            type=raw,value=${{ matrix.php }}
            type=raw,value=${{ matrix.php }}-${{ steps.date.outputs.today }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ vars.PUSH == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php }}
            PHP_EXTENSIONS=${{ env.PHP_EXTENSIONS }}
            RUNNER_VERSION=${{ steps.action_runner_version.outputs.runner_version }}
          cache-from: type=gha,scope=build-${{ matrix.php }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.php }}
